### ISSUE TITLE
Code review: simplify?

### ISSUE THREAD

**Issue by rdewijn** [tercen/zscore_scaling_operator#1]
@ginberg:
I think the code of this operator may be simplified somewat by uisng the standard scale operator of R
i.e. remove the do.scale function and use:

data %>% 
  mutate(z = scale(value) %>% as.numeric() ) %>%
  ungroup(.) %>% 
  select(.ri, .ci, !!new_col_name := z) %>%
  ctx$addNamespace() %>%
  ctx$save()

**Comment by ginberg** [comment]
good idea! I have adjusted the code
